name: Build Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Add MSBuild to path
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: .\vstudio_build.bat Debug

    - name: Archive portable
      uses: actions/upload-artifact@v2
      with:
        name: portable
        path: build/vstudio/Debug/MinTray.exe
