name: Build Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Add MSBuild to path
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: .\vstudio_build.bat Debug

    - name: Archive portable
      uses: actions/upload-artifact@v3
      with:
        name: portable
        path: build/vstudio/Debug/MinTray.exe
