name: Build Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Add MSBuild to path
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: .\vstudio_build.bat Release

    - name: Archive portable
      uses: actions/upload-artifact@v2
      with:
        name: portable
        path: build/vstudio/Release/MinTray.exe

    - name: Archive installer
      uses: actions/upload-artifact@v2
      with:
        name: installer
        path: build/vstudio/MinTray-*-win64.exe
