# Copyright 2020 Benbuck Nason
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish winget package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: wingetcreate
        run: |
          $wingetPackage = "Benbuck.Finestray"

          $gitToken = "${{ secrets.FINESTRAY_WINGET }}"

          $github = Invoke-RestMethod -uri "https://api.github.com/repos/benbuck/finestray/releases"
          $releaseVersions = $github | Where-Object -Property name -match 'v\d\.\d'
          $latestRelease = $releaseVersions | Select -First 1
          $firstAsset = $latestRelease | Select -ExpandProperty Assets -First 1
          $installerAsset = $firstAsset | Where-Object -Property name -match "Finestray-\d\.\d-win64\.exe"
          $installerUrl = $installerAsset | Select -ExpandProperty browser_download_url
          $version = $latestRelease.tag_name -ireplace '^v'
          $version = "$version.0.0"

          Write-Output "Installer URL: $installerUrl"
          Write-Output "Version: $version"

          Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          Write-Output ".\wingetcreate.exe update $wingetPackage --submit --version $version --urls "$installerUrl" --token ***"
          .\wingetcreate.exe update $wingetPackage --submit --version $version --urls "$installerUrl" --token $gitToken
